#pragma once

typedef enum Command Command;

enum Command {
  CommandSegment = 1,
  CommandReady,
  CommandLaunchReason,
  CommandWakeupSet,
  CommandWakeupSetResult,
  CommandWakeupCancel,
  CommandWakeupEvent,
  CommandWindowShow,
  CommandWindowHide,
  CommandWindowShowEvent,
  CommandWindowHideEvent,
  CommandWindowProps,
  CommandWindowButtonConfig,
  CommandWindowStatusBar,
  CommandWindowActionBar,
  CommandClick,
  CommandLongClick,
  CommandImagePacket,
  CommandCardClear,
  CommandCardText,
  CommandCardImage,
  CommandCardStyle,
  CommandVibe,
  CommandLight,
  CommandAccelPeek,
  CommandAccelConfig,
  CommandAccelData,
  CommandAccelTap,
  CommandMenuClear,
  CommandMenuClearSection,
  CommandMenuProps,
  CommandMenuSection,
  CommandMenuGetSection,
  CommandMenuItem,
  CommandMenuGetItem,
  CommandMenuSelection,
  CommandMenuGetSelection,
  CommandMenuSelectionEvent,
  CommandMenuSelect,
  CommandMenuLongSelect,
  CommandStageClear,
  CommandElementInsert,
  CommandElementRemove,
  CommandElementCommon,
  CommandElementRadius,
  CommandElementAngleStart,
  CommandElementAngleEnd,
  CommandElementBorderWidth,
  CommandElementText,
  CommandElementTextStyle,
  CommandElementImage,
  CommandElementAnimate,
  CommandElementAnimateDone,
  CommandVoiceStart,
  CommandVoiceStop,
  CommandVoiceData,
  NumCommands,
};
